docs/en-us/configure_introduction.md
docs/en-us/quick_start.md
docs/en-us/tubemq_user_guide.md
docs/zh-cn/configure_introduction.md
docs/zh-cn/quick_start.md
docs/zh-cn/tubemq_user_guide.md

Move [bdbStore] configs in master.ini to [replication] & [master], as bdb is an implementation detail, better not to bother users.
```
bdbRepGroupName         --> [replication].repGroupName
bdbNodeName             --> [replication].repNodeName
bdbNodePort             --> [replication].repNodePort
bdbHelperHost           --> [replication].repHelperHost
bdbEnvHome              --> [master].metaDataPath
bdbLocalSync            --> [replication].metaLocalSyncPolicy
bdbReplicaSync          --> [replication].metaReplicaSyncPolicy
bdbReplicaAck           --> [replication].repReplicaAckPolicy
bdbStatusCheckTimeoutMs --> [replication].repStatusCheckTimeoutMs
```
This PR update related docs:
```
docs/(zh-cn/en-us)/configure_introduction.md
docs/(zh-cn/en-us)/quick_start.md …
```

[TUBEMQ-166]Hide `bdbStore` configs in master.ini (docs)

---

site_config/home.jsx

change page quick start link from `/docs/tubeme_user_guide.html` to `/docs/quick_start.html`

[TUBEMQ-209] fix home page quick start link error

---

docs/en-us/quick_start.md
docs/zh-cn/quick_start.md

The PRIVATE_PORT `8123` should expose for broker's communication. 

[TUBEMQ-303]docker script should expose 8123 port

---

docs/en-us/quick_start.md

Replace "比如" with "e.g."
Thanks! :)

[TUBEMQ-335][Website] Missing translations in quick_start.md (en-us)

---

docs/zh-cn/architecture.md

[INLONG-606][website] Delete redundant description in architecture.html of zh-cn

---

docs/en-us/modules/agent/quick_start.md
docs/zh-cn/modules/agent/quick_start.md

Fixes https://github.com/apache/incubator-inlong/issues/1458
The http port in agent readme should be 8008 to be consistent with the code

[INLONG-1458][Agent] The http port in agent readme should be 8008 to be consistent with the code

---

docs/en-us/modules/dataproxy-sdk/quick_start.md
docs/zh-cn/modules/dataproxy-sdk/quick_start.md

Fixes https://github.com/apache/incubator-inlong/issues/1652
there is an unavailable link for the quick start of dataproxy-sdk
make link available 

[INLONG-1652][Dataproxy] there is an unavailable link for the quick start of dataproxy-sdk

---

download/main.md
download/release-0.11.0.md
i18n/zh-CN/docusaurus-plugin-content-docs-download/current/main.md
i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.11.0.md

Fixes #https://github.com/apache/incubator-inlong/issues/1690
add docs for releasing 0.11.0-incubating 
add release docs for inlong-0.11.0-incubating, including both english and chinese documents
only docs changes
- If yes, how is the feature documented? (docs )

[INLONG-1690] add release docs for inlong-0.11.0-incubating

---

README.md

Fixes #apache/incubator-inlong#1771
*(or)*
*(or)*
*(example:)* …

[INLONG-1771] Website readme error

---

docs/modules/dataproxy/architecture.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/architecture.md

Fixes apache/incubator-inlong#1808
*(or)*
*(or)*
*(example:)* …

[INLONG-1808] Optimize document of DataProxy about monitor metric

---

docs/modules/agent/architecture.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/architecture.md

Fixes [1853](https://github.com/apache/incubator-inlong/issues/1853)
should provide docs for jmx metrics in agent 
provide docs for jmx metrics in agent 

[InLong-1853][Feature][Agent] should provide docs for jmx metrics in agent 

---

docs/modules/agent/architecture.md

Fixes https://github.com/apache/incubator-inlong/issues/1864
Agent Website doc contains a typo
change ##4 Monitoring indicator configuration instructions
to 

[InLong-1864][Improve][Agent] Agent Website doc contains a typo

---

docs/modules/tubemq/http_access_api.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/http_access_api.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-0.11.0/modules/tubemq/http_access_api.md
versioned_docs/version-0.11.0/modules/tubemq/http_access_api.md

Fixes #apache/incubator-inlong#1919
*(or)*
*(or)*
*(example:)* …

[INLONG-1919] fix TubeMQ HTTP API xls can not download

---

docs/modules/dataproxy/quick_start.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/quick_start.md

Fixes #https://github.com/apache/incubator-inlong/issues/2126
*(or)*
*(or)*
*(example:)* …

[INLONG-2126] merge prepare_env.sh into dataproxy-start.sh

---

docs/quick_start/how_to_build.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/how_to_build.md

Fixes https://github.com/apache/incubator-inlong/issues/2220
*(or)*
*(or)*
*(example:)* …

[INLONG-2220] move dataproxy-sdk to inlong-sdk

---

docs/sdk/dataproxy-sdk/example.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/dataproxy-sdk/example.md

Fixes https://github.com/apache/incubator-inlong/issues/2455
*(or)*
*(or)*
*(example:)* …

[INLONG-2455] unify the module name for dataproxy

---

docs/modules/dataproxy/quick_start.md
docs/modules/manager/quick_start.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/quick_start.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/quick_start.md

Fixes https://github.com/apache/incubator-inlong/issues/2677
Change manager and dataproxy quick_start deployment.
*(or)*
*(or)*
*(example:)*
- If a feature is not applicable for …

[INLONG-2677] Manager get MQ cluster Info from database, remove local file configuration dependencies

---

docs/development/inlong_manager_shiro_plugin.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.0.0/development/inlong_manager_shiro_plugin.md

[INLONG-293] add Inlong manager user defined Shiro plug-in documentation
Fixes #293
*(or)*
*(or)*
*(example:)*
- If yes, …

[INLONG-293] add Inlong manager user defined Shiro plug-in documentation

---

docs/modules/dataproxy/quick_start.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/quick_start.md

Fixes [#3062](https://github.com/apache/incubator-inlong/issues/3062)
Merge the data_proxy_cluster table and the third_party_cluster table, and insert the data proxy cluster by OpenAPI.

[INLONG-3062][Manager] Merge the data_proxy_cluster table and the third_party_cluster table

---

docs/modules/dataproxy/overview.md
docs/modules/dataproxy/quick_start.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/overview.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/quick_start.md

Upgrading the documentation describing the default use of pulsar configuration
Fixes [#3067](https://github.com/apache/incubator-inlong/issues/3067)

[INLONG-3067][DataProxy] Upgrading the documentation of using the default Pulsar configuration

---

docs/design_and_concept/extend_sink_in_sort.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/extend_sink_in_sort.md

Fixes #309
*(or)*
*(or)*
*(example:)* …

[INLONG-309][doc] fix the title issue

---

docs/modules/dataproxy/quick_start.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/quick_start.md

Fixes [#3225](https://github.com/apache/incubator-inlong/issues/3225)
Support multiple IPs for the DataProxy cluster.

[INLONG-3225][Manager] Resolves multiple IPs when querying a DataProxy cluster

---

docs/modules/tubemq/quick_start.md

Fixes https://github.com/apache/incubator-inlong/issues/1655
Since the system interface does not support multiple languages, the relevant system screenshots are temporarily deleted, and supplements will be made after subsequent system support.

[INLONG-1655][Improve] TubeMQ Documents should use English pictures

---

docs/modules/sort-standalone/elasticsearch_example.md
docs/modules/sort-standalone/hive_example.md
docs/modules/sort-standalone/quick_start.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort-standalone/elasticsearch_example.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort-standalone/hive_example.md

[INLONG-3404][Website] Add Hive example document and ElasticSearch example document of Sort-standalone
Fixes apache/incubator-inlong#3404
*(or)*
*(or)*
*(example:)*
- If yes, how is …

[INLONG-3404][Website] Add Hive example document and ElasticSearch example document of Sort-standalone

---

docs/deployment/k8s.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/k8s.md

Fixes: https://github.com/apache/incubator-inlong/issues/3489
According to https://github.com/apache/incubator-inlong/pull/3646 , add k8s docs to official website.
Add k8s docs to official website.

[INLONG-3489] Add k8s docs to official website

---

docs/sdk/dataproxy-sdk/example.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/dataproxy-sdk/example.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.0.0/sdk/dataproxy-sdk/example.md
versioned_docs/version-1.0.0/sdk/dataproxy-sdk/example.md

Fixes #349 
*(or)*
*(or)*
*(example:)*
- If a feature is not documented yet in this PR, please create a followup …

[INLONG-349]Fix typo in docs

---

community/how-to-become-a-committer.md
community/how-to-contribute.md
src/pages/Home/index.jsx

Fixes: https://github.com/apache/incubator-inlong/issues/4706

[INLONG-4706][Website] Remove the "(incubating)" tag from the project name in the text content

---

community/how-to-release.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-release.md

- Fixes #518 
[INLONG-518] [Bug] the pgp server in release doc id deprecated and should upload connectors tar
[INLONG-518] [Bug] the pgp server in release doc id deprecated and should upload connectors tar

[INLONG-518][Bug] The pgp server in release doc id deprecated and should upload connectors tar

---

docusaurus.config.js

- Fixes #564(Maybe?!)
I think the problem description can be seen in the original issue, and I just did what I could on my end.
I suggest that organizations can choose a committer to manage and authorize algolia's keys. This would be a little more efficient.

[INLONG-564][Search] Update the key for algolia

---

docs/data_node/load_node/kafka.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/kafka.md

Title: [INLONG-583][Doc] Support dynamic topic and dynamic partition for KafkaLoadNode
Fixes #583
Support dynamic topic and dynamic partition for KafkaLoadNode
Add some comments about 'Support dynamic topic and dynamic partition for KafkaLoadNode' in 'kafka.md'
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with large payloads …

[INLONG-583][Doc] Support dynamic topic and dynamic partition for KafkaLoadNode

---

docs/deployment/docker.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/docker.md

Fixes #633 
Specify the `--platform` parameter of the `MySQL` image.
Update version of `docker-compose` to `2.4+`
By modifying the `--platform` parameter of the `MySQL` image, it can simulate `x86` instructions to build a docker image under different system architectures, and only need the same `docker-compose` script
In order to support compatible chip solutions, you need to update the docker-compose version to 2.4+
_No response_

[INLONG-633][Doc] Support running docker-compose on Arm Chip

---

docs/data_node/extract_node/mongodb-cdc.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/mongodb-cdc.md

Remove unsupported options in MongoDB CDC 2.3
- Fixes #702 
Some options have been removed in MongoDB CDC 2.3, for details please refer to this PR https://github.com/apache/inlong/pull/7515.
Remove the following options.
```
errors.tolerance
errors.log.enable
copy.existing.pipeline
copy.existing.max.threads
```

[INLONG-702][Doc] Remove unsupported options in MongoDB CDC 2.3

---

docs/data_node/load_node/starrocks.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/starrocks.md

- Fixes #727
There are some dirty data archiving options for StarRocks connector. Such as `dirty.igore`, `dirty.side-output.connector` and `dirty.side-output.labels` etc. The PR shows how to use them.
The English and Chinese document for Doris connector.
*(or)*
This change is already …

[INLONG-727][Doc] Dirty data archiving options description for StarRocks connector

---

src/pages/downloads/index.js

- Fixes #754 
Download page 1.7.0 'Release Date' error
Modify the date property in src/pages/downloads/index.js

[INLONG-754][Doc] Download page 1.7.0 'Release Date' error

---

docs/sdk/dataproxy-sdk/go.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-1.7.0/sdk/dataproxy-sdk/go.md

- Fixes #764
I have push a PR to add an INLONG DataProxy Golang SDK, and here adds the relative documents.
Add docs/sdk/dataproxy-sdk/go.md
Add i18n/zh-CN/docusaurus-plugin-content-docs/version-1.7.0/sdk/dataproxy-sdk/go.md
- Merge the PR files.
- Verify if the newly added file can be showed on the website.
- If yes, how is the feature documented? (not applicable)
- If a feature is not applicable for documentation, explain why? This is a documents PR.

[INLONG-WEBSITE-764][DataProxy] Add Golang SDK documents

---

docs/data_node/extract_node/sqlserver-cdc.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/sqlserver-cdc.md

[INLONG-768][Sort] Fix SQLServer key name of metadataKeys describe error
- Fixes #768 
Fix SQLServer key name of metadataKeys describe error. From the code, the metadata fields of SQL Server only include `table_name`, `schema_name`, `database_name`, and `op_ts`.
Remove the prefix `meta.`.

[INLONG-768][Sort] Fix SQLServer key name of metadataKeys describe error

---

docs/sdk/dataproxy-sdk/http.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/dataproxy-sdk/http.md

the dt param should be emphasized to be a time stamp in inlong web side http report example
* Update the http report guide*
- Fixes #772 
*the dt param should be emphasized to be a time stamp in inlong web side http report example*
*update the http report guide*
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? …

[INLONG-772][Doc] Update the http report guide

---

docs/data_node/extract_node/sqlserver-cdc.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/sqlserver-cdc.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/sqlserver.md

[INLONG-781][Doc][SqlServer] Describe tables using MarkDown
- Fixes #781
[INLONG-781][Doc][SqlServer] Describe tables using MarkDown
*(or)*
*(or)*
*(example:)*
- If a feature is not applicable …

[INLONG-781][Doc][SqlServer] Describe tables using MarkDown

---

docs/deployment/standalone.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/standalone.md

- Fixes #823 
Delete PostgreSQL, which is not support in inlong start script.
Delete PostgreSQL tips.
*(or)*
*(or)*
*(example:)*
- Does this pull …

[INLONG-823] Fix Database Tips for standalone deployment mode

---

docs/modules/tubemq/http_access_api.md

- Fixes #829 
fix wrong information
fix wrong information
*(or)*
*(or)*
*(example:)*
- If …

[INLONG-829][Doc] Fix wrong must information in admin_query_topic_info

---

docs/modules/tubemq/tubemq-manager/quick_start.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/tubemq-manager/quick_start.md

- Fixes #840
**Some parts of the original document are easily misleading to users, it has been modified and supplemented.**
**1、the previous text has been imported sql file, configuration instructions here, can be changed to:
-Add mysql information in conf/application.properties (you can directly use the database imported through sql/apache_tube_manager.sql)
2、Start the manager service according to the configuration above. If you change the applications.properties file in the middle of the process, you need to shut down and restart the manager service …

[INLONG-840][Doc] Adding more details to the tubemq-manager documentation

---

community/how-to-verify.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-verify.md

- Fixes #873 
Mvn clean package would run test before install
Sometimes we need to install first to run some tests
So install -DskipTests first and then use mvn test to run tests
install -DskipTests first and then use mvn test to run tests

[INLONG-873][Release] Update how-to-verify doc to use correct test command

---

docs/data_node/load_node/hbase.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/hbase.md

- Fixes #878 
*Update document of HBase load node.*
*Update document of HBase load node.*
This `hTable` is confusing. Actually it is `hbase_load_node`.

[INLONG-878][Improve] Update document of HBase load node

---

docs/data_node/extract_node/tube.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/tube.md

- Fixes #877 
*Update document of TubeMQ extract node*
*Update document of TubeMQ extract node*
According to these lines, `masterRpc` should be `master.rpc` and `groupId` should be `group.id`.
https://github.com/apache/inlong/blob/18c39ff593b1afb71063d85dc89adc4d589516cf/inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQOptions.java#L107
https://github.com/apache/inlong/blob/18c39ff593b1afb71063d85dc89adc4d589516cf/inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQOptions.java#L113

[INLONG-877][Improve] Update document of TubeMQ extract node

---

community/how-to-vote-a-committer-pmc.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-vote-a-committer-pmc.md

- Fixes #908
Improve how to vote committer doc make module name configurable
improved the ${Candidate_Module_Name} module, not manager module by default

[INLONG-908] Improve how to vote committer doc make module name configurable

---

docs/development/extension_sort/extension_connector.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/development/extension_sort/extension_connector.md

[INLONG-1020][Doc] Add doc of extension connector

---

docs/sdk/dataproxy-sdk/java.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/dataproxy-sdk/java.md

Fixes #1046 
As [[Bug][SDK] Fix incorrect usage of isLocalVisit variable in client example of dataproxy-sdk module #11110](https://github.com/apache/inlong/issues/11110) shows, the current dataproxy java sdk documentation description has a few things that need to be updated
- Updated `getMessageSender` function content
- Replaced `isLocalVisit` with `requestByHttp` to better describe parameter meanings
- Updated description about `close()`
*(example:)* …

[INLONG-1046][Doc] Update DataProxy java SDK documentation

---

docs/modules/sort/metrics.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/metrics.md

Fixes #1057 
New flink metrics has been added to inlong-sort module. Relavant documentation is provided to explain this change.
- Added documentation for newly-added flink source/sink metrics
- Updated the Chinese version of flink sql example
- Made some statements more straight forward

[INLONG-1057][Doc] Add documentation for newly introduced source and sink metrics in inlong-sort

---

docs/quick_start/offline_data_sync/pulsar_mysql_example.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/offline_data_sync/pulsar_mysql_example.md
i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0.0/quick_start/offline_data_sync/pulsar_mysql_example.md
versioned_docs/version-2.0.0/quick_start/offline_data_sync/pulsar_mysql_example.md

Fixes #1074 
Revise the expression errors in the document.
Both Next and 2.0.0 have this issue. Taking the Next version as an example:
*(example:)*

[INLONG-1074][Doc] Fix incorrect expression in Offline Data Synchronization example

---

src/pages/downloads/index.js

Fixes #1069 
Connector Binary file v1.18 is not listed in download page. However, they have been released on the maven repository of apache inlong. It should be added to reflect this change, while also resolving confusions as some examples in the website require users to use connector-v1.18
Added one more row for Connector Binary file v1.18

[INLONG-1069][Doc] Add Connector Binary file v1.18 to download page

---

docs/modules/sort/metrics.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/metrics.md

Fixes #1067 
Since changes to those above-mentioned cdcs are made during the release preparation of inlong, they are not included in release 2.0.0, but will be included in release 2.1.0 release. Adding documentation to reflect this change.

[INLONG-1067][Doc] Add sqlserver and mongodb to supported list of newly-introduced source metrics

---

docs/quick_start/data_ingestion/file_pulsar_clickhouse_example.md
docs/quick_start/data_ingestion/mysql_kafka_clickhouse_example.md
docs/quick_start/offline_data_sync/airflow_example.md
docs/quick_start/offline_data_sync/dolphinscheduler_example.md
docs/quick_start/offline_data_sync/quartz_example.md
docs/quick_start/realtime_data_sync/mysql_clickhouse_example.md
docs/quick_start/realtime_data_sync/mysql_iceberg_example.md
docs/quick_start/realtime_data_sync/mysql_starrocks_example.md
docs/quick_start/realtime_data_sync/pulsar_clickhouse_example.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/data_ingestion/file_pulsar_clickhouse_example.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/data_ingestion/mysql_kafka_clickhouse_example.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/offline_data_sync/airflow_example.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/offline_data_sync/dolphinscheduler_example.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/offline_data_sync/quartz_example.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/realtime_data_sync/mysql_clickhouse_example.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/realtime_data_sync/mysql_iceberg_example.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/realtime_data_sync/mysql_starrocks_example.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/realtime_data_sync/pulsar_clickhouse_example.md

[INLONG-1119][Doc] Fix Quick Start Chapter 
