apache/inlong-website

docs/zh-cn/architecture.md, docs/zh-cn/consumer_example.md, docs/zh-cn/contact.md, docs/zh-cn/deployment.md, docs/zh-cn/producer_example.md, docs/zh-cn/quick_start.md
fix:  [TUBEMQ-181](https://issues.apache.org/jira/browse/TUBEMQ-181)
Add chinese documents to zh-cn folder.
**Related docs**:
modified:   docs/zh-cn/architecture.md
modified:   docs/zh-cn/consumer_example.md
modified:   docs/zh-cn/contact.md
modified:   docs/zh-cn/deployment.md
modified:   docs/zh-cn/producer_example.md
modified:   docs/zh-cn/quick_start.md
=> Add chinese documents

docs/en-us/quick_start.md, docs/zh-cn/quick_start.md
1. Merge the contents of docs user guide and quick start
2. Update start/stop service commands
3. Fix demo example
=> [TUBEMQ-201] [Website] Adjust user guide & fix demo example

docs/en-us/development/how-to-contribute.md, md_json/docs.json
fix link page contact link from /contact to ../contact.html
=> [TUBEMQ-211] fix link to page contact in page how-to-contribute.html

docs/en-us/consumer_example.md, docs/en-us/producer_example.md, docs/zh-cn/consumer_example.md, docs/zh-cn/producer_example.md, md_json/docs.json
add format java in doc consumer_example and producer_example
=> [TUBEMQ-212] add format java in doc consumer_example and producer

docs/en-us/error_code.md
[TUBEMQ-207] [website] Translate error_code.md
=> [TUBEMQ-207] [website] Translate error_code.md

docs/en-us/development/how-to-release.md, docs/zh-cn/development/how-to-release.md
Reverts apache/incubator-tubemq-website#52
=> Revert "[TUBEMQ-367][website] Update docs how-to-release"

docs/en-us/configure_introduction.md, docs/zh-cn/configure_introduction.md
Add parameter rebalanceParallel introduction in master.ini
=> [TUBEMQ-464]Add parameter rebalanceParallel in master.ini

docs/en-us/development/how-to-release.md, docs/zh-cn/development/how-to-release.md
Change DISCLAIMER-WIP to DISCLAIMER
=> [TUBEMQ-527] Update checklist

docs/en-us/contact.md, docs/en-us/development/how-to-become-a-committer.md, docs/en-us/development/how-to-contribute.md, docs/en-us/development/how-to-release.md, docs/en-us/development/how-to-vote-a-committer-ppmc.md, docs/zh-cn/contact.md, docs/zh-cn/development/how-to-become-a-committer.md, docs/zh-cn/development/how-to-contribute.md, docs/zh-cn/development/how-to-release.md, docs/zh-cn/development/how-to-vote-a-committer-ppmc.md, site_config/development.js
=> [INLONG-1394][Platform] Update the document after Migrate InLong Issue

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md
=> add issue and pull template for website

docs/en-us/modules/agent/quick_start.md, docs/en-us/modules/dataproxy/quick_start.md, docs/en-us/modules/manager/architecture.md, docs/en-us/modules/manager/quick_start.md, docs/en-us/quick_start.md, docs/zh-cn/modules/agent/quick_start.md, docs/zh-cn/modules/dataproxy/quick_start.md, docs/zh-cn/modules/manager/architecture.md, docs/zh-cn/modules/manager/quick_start.md, docs/zh-cn/quick_start.md
Fixes #122
Modify the deployment document of InLong-Manager
`docs/zh-cn/modules/manager/quick_start.md`
=> Modify the deployment document of InLong-Manager

docs/en-us/development/how-to-release.md, docs/zh-cn/development/how-to-release.md
Fixes https://github.com/apache/incubator-inlong/issues/1511
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1511] fix release guild documents

docs/en-us/example.md, site_config/docs.js
Fix  [apache-inlong #1508](https://github.com/apache/incubator-inlong/issues/1508).
Add English example.md
=> [INLONG-1508] Add English example.md

docs/en-us/download/download.md, docs/en-us/download/release-0.10.0.md, docs/zh-cn/download/download.md, docs/zh-cn/download/release-0.10.0.md
Fixes https://github.com/apache/incubator-inlong/issues/1493
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1493] Modify download&release notes for 0.10.0

site_config/docs.js
Fixes https://github.com/apache/incubator-inlong/issues/1554
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1554] remove the Console Introduction for manager

docs/en-us/download/download.md, docs/en-us/download/release-0.9.0.md, docs/zh-cn/download/download.md, docs/zh-cn/download/release-0.9.0.md
=> [INLONG-1575] Modify the download url of version 0.9.0

.github/workflows/deploy.yml
Fixes #apache/incubator-inlong#1638
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1638] Adapt new github action command

docusaurus.config.js
Fixes #apache/incubator-inlong#1668
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1668] Adapt quick edit link #1668

development/how-to-release.md
Fixes #168 
fix some incorrect links in the release template
modify the incorrect links
This change is a trivial rework  no more tests needed
- If yes, how is the feature documented? ( not documented)
=> fix incorrect link in release template

docs/modules/agent/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/quick_start.md
Fixes https://github.com/apache/incubator-inlong/issues/1742
Modify bid and tid to inlongGroupId and inlongStreamId
Modify bid and tid to inlongGroupId and inlongStreamId
=> [INLONG-1742] Modify bid and tid to inlongGroupId and inlongStreamId for office-web documents

docs/modules/dataproxy-sdk/architecture.md, docs/modules/dataproxy/architecture.md, docs/modules/tubemq/clients_java.md, docs/modules/tubemq/error_code.md, docs/modules/tubemq/http_access_api.md, docs/user_guide/example.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy-sdk/architecture.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/architecture.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_guide/example.md
Fixes https://github.com/apache/incubator-inlong/issues/1744
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1744] Modify bid and tid (or dsid) to inlongGroupId and inlongStreamId for dataproxy doc

.github/workflows/deploy.yml
…that the node version needs to be upgraded
Fixes #apache/incubator-inlong#1752
*(or)*
*(or)*
*(example:)*
- If yes, how …
=> [INLONG-1752] The official website action failed to build

download/release-0.10.0.md, download/release-0.11.0.md, download/release-0.3.0.md, download/release-0.5.0.md, download/release-0.6.0.md, download/release-0.7.0.md, download/release-0.8.0.md, download/release-0.9.0.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.10.0.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.11.0.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.3.0.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.5.0.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.6.0.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.7.0.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.8.0.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.9.0.md
Fixes #https://github.com/apache/incubator-inlong/issues/1754
fix the navigation error of the download page
fix the navagition error of the download page
- If yes, how is the feature documented? (docs)
=> [InLong-1754] fix the navigation error of download page

development/how-to-release.md, i18n/zh-CN/docusaurus-plugin-content-docs-development/current/how-to-release.md
Fixes https://github.com/apache/incubator-inlong/issues/1755
fix broken link in the template
fix broken link in the template, including
- download link
- release not link
- If yes, how is the feature documented? (docs)
=> [INLONG-1755] fix broken link

README.md
Fixes #apache/incubator-inlong#1771
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1771] Website readme error

docusaurus.config.js
Fixes https://github.com/apache/incubator-inlong/issues/1764
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1764] Use black for code block background style

docusaurus.config.js, i18n/zh-CN/docusaurus-theme-classic/navbar.json
Fixes https://github.com/apache/incubator-inlong/issues/1583
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1583] add blog tab

docusaurus.config.js, src/pages/versions/index.js
Fixes https://github.com/apache/incubator-inlong/issues/1802
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1802] Optimize document version management

src/pages/Home/index.jsx, src/pages/Home/index.less
Fixes https://github.com/apache/incubator-inlong/issues/1809
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1809] Adjust the font style of the official home page

docs/modules/tubemq/http_access_api.md, docs/modules/tubemq/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/configure_introduction.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/deployment.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/error_code.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/http_access_api.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/quick_start.md
Fixes: https://github.com/apache/incubator-inlong/issues/1822
=> [INLONG-1822] Optimize the table formatting in some MD documents

docs/modules/tubemq/http_access_api.md
See: https://github.com/apache/incubator-inlong/issues/1822
Fix the bug.
=> [INLONG-1822] Optimize the table formatting in some MD documents (addenum)

development/how-to-vote-a-committer-ppmc.md, docs/modules/tubemq/http_access_api.md, i18n/zh-CN/docusaurus-plugin-content-docs-development/current/how-to-vote-a-committer-ppmc.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/http_access_api.md
See: https://github.com/apache/incubator-inlong/issues/1824
=> [INLONG-1824] Refine the how-to-vote-a-committer-ppmc.md

blog/apache-inlong-0.11.0.md, i18n/zh-CN/docusaurus-plugin-content-blog/apache-inlong-0.11.0.md
fixes https://github.com/apache/incubator-inlong/issues/1815
This change is a trivial rework/code cleanup without any test coverage.
*(or)*
*(or)*
*(example:)*
- Does this pull request introduces a new feature? (yes / no) …
=> [INLONG-1815] translate the 0.11.0 release blog

development/how-to-become-a-committer.md
Fixes https://github.com/apache/incubator-inlong/issues/1658
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1658] translate the how-to-become-a-committer

docusaurus.config.js
Fixes https://github.com/apache/incubator-inlong/issues/1830
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1830] Add a star reminder

blog/new-committer-join.md, docusaurus.config.js, i18n/zh-CN/docusaurus-plugin-content-blog/new-committer-join.md
Fixes https://github.com/apache/incubator-inlong/issues/1840
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1840] add a Welcome committer articles to official website blog

i18n/zh-CN/docusaurus-plugin-content-docs-development/current/how-to-vote-a-committer-ppmc.md
=> [INLONG-205]Add a space between the URL and Chines period.

i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-0.11.0/modules/tubemq/quick_start.md
The detail see: https://github.com/apache/incubator-inlong/issues/1865
=> [INLONG-1865][Improve] There are several errors in TubeMQ's guidance document

src/pages/users/index.js, src/pages/users/index.less
Fixes https://github.com/apache/incubator-inlong/issues/1878
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1878] Optimize user display page layout style

docs/modules/tubemq/tubemq_metrics.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/tubemq_metrics.md
=> [INLONG-218]Add Metric documents of TubeMQ

docusaurus.config.js, i18n/zh-CN/docusaurus-theme-classic/navbar.json, package.json, src/pages/team/config.json, src/pages/team/index.js, src/pages/team/index.less
Fixes https://github.com/apache/incubator-inlong/issues/1833
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1833] Add team tab to the official website and add a team page

development/how-to-release.md
fix  [[Improve][translation] the guide of how-to-release should be translated into English #1660](https://github.com/apache/incubator-inlong/issues/1660)
translate how-to-release to English
=> [INLONG-1660][WebSite] translate how-to-release to english

docs/modules/agent/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/overview.md
issue: [#1712](https://github.com/apache/incubator-inlong/issues/1712)
pr: [#1866](https://github.com/apache/incubator-inlong/pull/1866)
- `docs/modules/agent/overview.md`
- `i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/overview.md`
=> [INLONG-1712][Agent][Docs] Add agent prometheus metrics doc

docs/introduction.md, src/pages/Home/config.json
Fixes https://github.com/apache/incubator-inlong/issues/2034
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2034] Update the definition of InLong more clearly

docs/modules/dataproxy/quick_start.md, docs/modules/manager/quick_start.md, docs/modules/sort/quick_start.md, docs/modules/tubemq/tubemq-manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/tubemq-manager/quick_start.md
Fixes https://github.com/apache/incubator-inlong/issues/2042
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2042] fix the deployment guide mistakes

.github/workflows/deploy.yml
Fixes #234 #235
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / …
=> [INLONG-234] Update peaceiris/actions-gh-pages version

development/how-to-release.md, i18n/zh-CN/docusaurus-plugin-content-docs-development/current/how-to-release.md
=> [INLONG-WEBSITE-237]Fix incorrect KEYS links in release template

docs/modules/dataproxy/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/quick_start.md
Fixes https://github.com/apache/incubator-inlong/issues/2063
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2043] update the deployment guide for DataProxy

download/main.md, download/release-0.10.0.md, download/release-0.11.0.md, download/release-0.12.0.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/main.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.10.0.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.11.0.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.12.0.md
Fixes https://github.com/apache/incubator-inlong/issues/1945
=> [INLONG-1945]Modify download&release notes for 0.12.0

docs/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/quick_start.md
Fixes #https://github.com/apache/incubator-inlong/issues/2072
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2072] update the deployment guide for sort

docs/modules/agent/file.md, docs/modules/agent/quick_start.md, docs/quick_start/hive_example.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/file.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/hive_example.md
Fixes #https://github.com/apache/incubator-inlong/issues/2080
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2080] fix the wrong keys for file agent

i18n/zh-CN/docusaurus-plugin-content-docs/version-0.12.0.json
Fixes https://github.com/apache/incubator-inlong/issues/2088
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2088] Modify the version number issue

docs/deployment/bare_metal.md, docs/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/bare_metal.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/quick_start.md
Fixes apache/incubator-inlong#2183
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2183][Feature][InLong-Sort] Bump flink version to 1.13.5

docs/deployment/bare_metal.md, docs/introduction.md, docs/modules/dashboard/_category_.json, docs/modules/dashboard/overview.md, docs/modules/dashboard/quick_start.md, docs/modules/website/_category_.json, docs/quick_start/how_to_build.md, i18n/zh-CN/docusaurus-plugin-content-docs/current.json, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/bare_metal.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/introduction.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dashboard/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dashboard/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/how_to_build.md
Fixes https://github.com/apache/incubator-inlong/pull/2197
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2196] move website to dashboard

docs/deployment/docker.md, docs/modules/dashboard/quick_start.md, docs/modules/manager/quick_start.md, docs/quick_start/how_to_build.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/docker.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dashboard/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/how_to_build.md
Fixes https://github.com/apache/incubator-inlong/issues/2210
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2210] package inlong-manager-web as inlong-manager

docs/modules/agent/sql.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/sql.md
Fixes (https://github.com/apache/incubator-inlong/issues/2169)
should provide docs for agent db sql collect
should provide docs for agent db sql collect
=> [INLONG-2169][Feature][Agent] should provide docs for agent db sql collect

docs/modules/sort-standalone/_category_.json, docs/modules/sort-standalone/overview.md, docs/modules/sort-standalone/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort-standalone/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort-standalone/quick_start.md
Fixes apache/incubator-inlong#2170
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2170] add Inlong-Sort-standalone document.

docs/modules/sort-standalone/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort-standalone/quick_start.md
Fixes apache/incubator-inlong#2252
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2252] Remove <> character in sort-standalone quick_start.md.

docs/administration/_category_.json, docs/design_and_concept/basic_concept.md, docs/development/_category_.json, docs/development/inlong_msg.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/basic_concept.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/development/inlong_msg.md
Fixes #https://github.com/apache/incubator-inlong/issues/2271
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2271] move TDMsg to InLongMsg

docs/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/standalone.md
update standalone.md
Fixes https://github.com/apache/incubator-inlong/issues/2301
*(or)*
*(or)*
*(example:)*
- If yes, how …
=> [INLONG-2301] add standalone deployment guide

docs/deployment/bare_metal.md, docs/modules/audit/overview.md, docs/modules/audit/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/bare_metal.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/quick_start.md
Fixes apache/incubator-inlong#2352
add audit introduction
=>  [INLONG-2352] [InLong audit] add audit introduction

docs/modules/dataproxy/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/quick_start.md
Fixes #https://github.com/apache/incubator-inlong/issues/2338
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2338] modify default dataproxy address

docs/deployment/standalone.md, docs/modules/agent/quick_start.md, docs/modules/audit/quick_start.md, docs/modules/dataproxy/quick_start.md, docs/modules/manager/quick_start.md, docs/modules/sort/quick_start.md, docs/quick_start/how_to_build.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/how_to_build.md
Fixes https://github.com/apache/incubator-inlong/issues/2361
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2361] optimize the guide for configure audit

development/how-to-verify.md, i18n/zh-CN/docusaurus-plugin-content-docs-development/current/how-to-verify.md
Fixes https://github.com/apache/incubator-inlong/issues/2398
=> [INLONG-2398][WEBSITE][Improve] Add the requirement to execute mvn test

package.json
Fixes https://github.com/apache/incubator-inlong/issues/2399
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2399] update the docusaurus version

.github/workflows/deploy.yml
Fixes #https://github.com/apache/incubator-inlong/issues/2399
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2399] update the github action node version

docs/deployment/docker.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/docker.md
issue: [#2509](https://github.com/apache/incubator-inlong/issues/2509)
pr: [#2511](https://github.com/apache/incubator-inlong/pull/2511)
Add documentation for Audit on Docker Compose.
- `docs/deployment/docker.md`
- `i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/docker.md`
=> [INLONG-2509][DockerCompose][Docs] Add documentation for Audit on Docker Compose

docs/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/standalone.md
Fixes #1234
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1234] update deployment standalone.md

docs/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/quick_start.md
Fixes apache/incubator-inlong#2561
Update deploy settings of InLong-Sort
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2561][Sort] Update deploy settings of InLong-Sort

download/main.md, download/release-0.12.0.md, download/release-1.0.0.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/main.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-0.12.0.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-1.0.0.md
Fixes #https://github.com/apache/incubator-inlong/issues/2367
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2467] add download&release notes for 1.0.0

download/release-1.0.0.md, i18n/zh-CN/docusaurus-plugin-content-docs-download/current/release-1.0.0.md
Fixes https://github.com/apache/incubator-inlong/issues/2590
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2590] remove the special character

package.json
Fixes https://github.com/apache/incubator-inlong/issues/2752
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2752] update docusaurus-plugin version

docs/modules/agent/quick_start.md, docs/modules/audit/quick_start.md, docs/modules/manager/quick_start.md, docs/modules/tubemq/tubemq-manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/tubemq-manager/quick_start.md
Fixes https://github.com/apache/incubator-inlong/issues/2784
*(or)*
*(or)*
*(example:)* …
=> [INLONG-2784] Replace MySQL with PostgreSQL

src/pages/team/index.js
Fixes https://github.com/apache/incubator-inlong/issues/3119
*(or)*
*(or)*
*(example:)* …
=> [INLONG-3119] Official website team page support request multiple times

community/how-to-become-a-committer.md, community/how-to-commit.md, community/how-to-contribute.md, community/how-to-release.md, community/how-to-report-issues.md, community/how-to-subscribe.md, community/how-to-verify.md, community/how-to-vote-a-committer-ppmc.md, docs/introduction.md, docs/modules/audit/_category_.json, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-become-a-committer.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-commit.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-contribute.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-release.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-report-issues.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-subscribe.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-verify.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-vote-a-committer-ppmc.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/introduction.md
Fixes https://github.com/apache/incubator-inlong/issues/3133
*(or)*
*(or)*
*(example:)* …
=> [INLONG-3133] Add How to Report Issues guides document and update the community files

docs/development/inlong_manager_shiro_plugin.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/development/inlong_manager_shiro_plugin.md
[INLONG-307]add Add Shiro interface for manager authorization]
Fixes #307
*(or)*
*(or)*
*(example:)*
- If yes, how is the …
=> [INLONG-307] add Add Shiro interface for manager authorization

docs/design_and_concept/extend_sink_in_sort.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/extend_sink_in_sort.md
Fixes #295 
*(or)*
*(or)*
*(example:)* …
=> [INLONG-295] Add document for introducing how to extend a new type of sink in sort

.github/workflows/ci_build.yml, .github/workflows/deploy.yml
Fixes https://github.com/apache/incubator-inlong/issues/3172
*(or)*
*(or)*
*(example:)* …
=> [INLONG-3712] add pull_request CI for website

src/pages/Home/index.jsx, src/pages/Home/index.less
Fixes https://github.com/apache/incubator-inlong/issues/3276
*(or)*
*(or)*
*(example:)* …
=> [INLONG-3276] Official website homepage add twitter contact

docs/modules/audit/overview.md, docs/modules/audit/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/quick_start.md
Fixes https://github.com/apache/incubator-inlong/issues/3288
*(or)*
*(or)*
*(example:)* …
=> [INLONG-3288][Audit] Support TubMQ for website

docs/modules/tubemq/configure_introduction.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/configure_introduction.md
Fixes: https://github.com/apache/incubator-inlong/issues/3354
=> [INLONG-3354][TubeMQ]Update master.ini configuration guidelines document

docs/modules/tubemq/configure_introduction.md, docs/modules/tubemq/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/configure_introduction.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/quick_start.md
Fixes https://github.com/apache/incubator-inlong/issues/3363
=> [INLONG-3363][TubeMQ]Added how to use optional BDB components and documentation

docs/deployment/docker.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/docker.md
Fixes https://github.com/apache/incubator-inlong/issues/3412
*(or)*
*(or)*
*(example:)* …
=> [INLONG-3412][Docker] optimize the docker-compose for registering component

docs/modules/audit/quick_start.md, docs/modules/dataproxy/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/quick_start.md
Fixes https://github.com/apache/incubator-inlong/issues/3417
=> [INLONG-3417][Docker] add audit configuration for other component docker image

docs/modules/agent/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/quick_start.md
Fixes #328 
[INLONG-328]Add Tubemanager Sql instructions
[INLONG-328]Add Tubemanager Sql instructions
=> [INLONG-328]Add Tubemanager Sql instructions

docs/deployment/bare_metal.md, docs/deployment/standalone.md, docs/modules/agent/quick_start.md, docs/modules/dataproxy/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/quick_start.md
Fixes https://github.com/apache/incubator-inlong/issues/3481
*(or)*
*(or)*
*(example:)* …
=> [INLONG-3481] optimize the standalone script

docs/sdk/manager-sdk/example.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/manager-sdk/example.md
Fixes #3516
*(or)*
*(or)*
*(example:)* …
=> [INLONG-3516][Manager] rename the manager-client-test to manager-client-example

src/pages/team/index.js
=> [INLONG-336] Update InLong Team member information

docs/design_and_concept/how_to_write_plugin_dashboard.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/how_to_write_plugin_dashboard.md
Fixes #apache/incubator-inlong#3670
=> [INLONG-3670] Add dashboard plugin docs to official website

docs/user_guide/command_line_tools.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_guide/command_line_tools.md
Fixes #346 
Add documentation for command-lin tools.
=> [INLONG-346][Manager] Add documentation for command-lin tools

docs/introduction.md, docs/modules/manager/quick_start.md, docs/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/introduction.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/quick_start.md
Fixes https://github.com/apache/incubator-inlong/issues/3767
*(or)*
*(or)*
*(example:)* …
=> [INLONG-3767][Doc] Add supported data nodes guide for InLong

docs/user_guide/command_line_tools.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_guide/command_line_tools.md
Fixes #353 
Update the documentation for `-s --status`
=> [INLONG-353][Manager] Update the documentation for managerctl

docs/data_node/extract_node/auto_push.md, docs/data_node/extract_node/file.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/auto_push.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/file.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/dataproxy-sdk/example.md
Fixes #355
*(or)*
*(or)*
*(example:)* …
=> [INLONG-355][Doc] Add Auto Push Description

docs/data_node/load_node/auto_consumption.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/auto_consumption.md
Fixes #363
*(or)*
*(or)*
*(example:)* …
=> [INLONG-363][Doc] fix the title error for auto Consumption

docs/modules/manager/quick_start.md
=> [INLONG-WEBSITE-367] Remove redundant contents

community/how-to-vote-a-committer-ppmc.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-vote-a-committer-ppmc.md
Fixes https://github.com/apache/incubator-inlong/issues/4073
=> [INLONG-4073][Doc] Modify the invitation email templates of Committer or PPMC

docusaurus.config.js
Fixes #apache/incubator-inlong#4150
=> [INLONG-4150][Office-Website] Automatically identify version number sorting #4150

docs/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/quick_start.md
Fixes #371
Modify the message queue registration demo, Solve the registration message queue bug
=> [INLONG-371][Manager] Modify the message queue registration demo

docs/modules/tubemq/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/quick_start.md
Fixes https://github.com/apache/incubator-inlong/issues/1839
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1839][Doc] Add defEthName config guide

.github/workflows/ci_build.yml, .github/workflows/deploy.yml, package.json
Fixes #apache/incubator-inlong#4426
=> [INLONG-4426][Website] Update CI Nodejs Version

docs/sdk/dataproxy-sdk/example.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/dataproxy-sdk/example.md
=> [INLONG-389][Website] Update DataProxy example

docusaurus.config.js
Fixes https://github.com/apache/incubator-inlong/issues/1831
*(or)*
*(or)*
*(example:)* …
=> [INLONG-1831][Website] Add official website content search button

i18n/zh-CN/docusaurus-plugin-content-blog/apache-inlong-0.11.0.md, i18n/zh-CN/docusaurus-plugin-content-blog/apache-inlong-0.12.0.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-0.11.0/user_guide/quick_start.md, versioned_docs/version-0.11.0/user_guide/quick_start.md
Fixes https://github.com/apache/incubator-inlong-website/issues/398
*(or)*
*(or)*
*(example:)*
- If yes, how is the …
=> [INLONG-398][Website] Blog image display

docusaurus.config.js, src/css/custom.css, src/pages/index.jsx
Fixes #apache/incubator-inlong#4616
=> [INLONG-4616] Set Apache events on footer

docs/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/quick_start.md
Fixes #413 
Update sort deployment doc
modify sort deployment doc
=> [INLONG-413][Sort] Update sort deployment doc

docs/data_node/extract_node/pulsar.md, docs/data_node/load_node/iceberg.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/pulsar.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/iceberg.md
Fixes #407 
Add pulsar iceberg docs
Add pulsar iceberg docs
=> [INLONG-407][Sort] Add pulsar and iceberg docs

docs/design_and_concept/basic_concept.md, docs/introduction.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/basic_concept.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/introduction.md
Fixes https://github.com/apache/incubator-inlong/issues/4696
*(or)*
*(or)*
*(example:)* …
=> [INLONG-4696][Doc] Update the supported data nodes

src/pages/team/index.js
Fixes: https://github.com/apache/incubator-inlong/issues/4705
=> [INLONG-4705][Website] Adjust InLong Team member list

src/pages/team/index.js
Fixes: https://github.com/apache/incubator-inlong/issues/4705
=> [INLONG-4705][Website] Adjust InLong Team member list(addendum)

docusaurus.config.js
- Fixes: https://github.com/apache/incubator-inlong/issues/4703
=> [INLONG-4703][Website] Adjust the footer content of the home page

docs/design_and_concept/how_to_extend_data_node_for_manager.md, docs/design_and_concept/how_to_extend_data_node_for_sort.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/how_to_extend_data_node_for_manager.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/how_to_extend_data_node_for_sort.md.md
Fixes https://github.com/apache/inlong/issues/4716
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? …
=> [INLONG-4716][Doc] Update the plugin file name

docs/design_and_concept/how_to_extend_data_node_for_manager.md, docs/design_and_concept/how_to_extend_data_node_for_sort.md, docs/design_and_concept/how_to_write_plugin_dashboard.md, docs/modules/dataproxy/overview.md, docs/modules/sort/example.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/how_to_extend_data_node_for_manager.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/how_to_extend_data_node_for_sort.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/how_to_write_plugin_dashboard.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/example.md
Fixes #439
*(or)*
*(or)*
*(example:)* …
=> [INLONG-439][Doc] Update the plugin and modules documents

docs/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2.0/modules/manager/quick_start.md, versioned_docs/version-1.2.0/modules/manager/quick_start.md
Fixes #445
*(or)*
*(or)*
*(example:)* …
=> [INLONG-445][Manager] Add sort connectors guide for manager

community/how-to-vote-a-committer-pmc.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-vote-a-committer-pmc.md
Fixes: https://github.com/apache/inlong/issues/4746
=> [INLONG-4746][Website] Modify the how-to-vote-a-committer-pmc file

community/how-to-release.md, community/how-to-verify.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-release.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-verify.md
Fixes: https://github.com/apache/inlong/issues/4710
=> [INLONG-4710][Website] Modify how to release and verify

docs/modules/manager/quick_start.md, versioned_docs/version-1.2.0/modules/manager/quick_start.md
Fixes #453 
Correct maven jar url
remove blankspace in maven jar url
=> [INLONG-453][Website] Fix the incorrect URL for the MySQL jar

docs/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2.0/deployment/standalone.md, versioned_docs/version-1.2.0/deployment/standalone.md
- Fixes #461
*(or)*
*(or)*
*(example:)* …
=> [INLONG-461][Doc] Update the registered URL for the MQ

docs/deployment/standalone.md, docs/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2.0/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2.0/modules/sort/quick_start.md, versioned_docs/version-1.2.0/deployment/standalone.md, versioned_docs/version-1.2.0/modules/sort/quick_start.md
- Fixes #463
*(or)*
*(or)*
*(example:)* …
=> [INLONG-463][Doc] Update the guide for download the sort connectors

docs/modules/audit/overview.md, docs/modules/audit/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/quick_start.md
- Title: https://github.com/apache/inlong/pull/4747
- Fixes #4741
*(or)*
*(or)*
*(example:)* …
=> [INLONG-4741][Audit] AuditStore support ClickHouse sink

docs/modules/tubemq/tubemq-manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/tubemq-manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2.0/modules/tubemq/tubemq-manager/quick_start.md, versioned_docs/version-1.2.0/modules/tubemq/tubemq-manager/quick_start.md
- Fixes https://github.com/apache/inlong-website/issues/470
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with …
=> [INLONG-470][TubeMQ] Modify tube manager dependency description

docusaurus.config.js
- Fixes https://github.com/apache/inlong-website/issues/477
=> [INLONG-477][Website] Remove the top star

docusaurus.config.js
- Fixes https://github.com/apache/inlong-website/issues/481
=> [INLONG-481][Website] Change the header navigation bar title

docs/data_node/extract_node/sqlserver-cdc.md, docs/data_node/load_node/hive.md, docs/deployment/bare_metal.md, docs/deployment/standalone.md, docs/quick_start/how_to_build.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/sqlserver-cdc.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/hive.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/bare_metal.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/how_to_build.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-0.12.0/quick_start/how_to_build.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.0.0/quick_start/how_to_build.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.1.0/deployment/bare_metal.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.1.0/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.1.0/quick_start/how_to_build.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2.0/data_node/extract_node/sqlserver-cdc.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2.0/data_node/load_node/hive.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2.0/deployment/bare_metal.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2.0/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2.0/quick_start/how_to_build.md, versioned_docs/version-0.12.0/quick_start/how_to_build.md, versioned_docs/version-1.0.0/quick_start/how_to_build.md, versioned_docs/version-1.1.0/deployment/bare_metal.md, versioned_docs/version-1.1.0/deployment/standalone.md, versioned_docs/version-1.1.0/quick_start/how_to_build.md, versioned_docs/version-1.2.0/data_node/extract_node/sqlserver-cdc.md, versioned_docs/version-1.2.0/data_node/load_node/hive.md, versioned_docs/version-1.2.0/deployment/bare_metal.md, versioned_docs/version-1.2.0/deployment/standalone.md, versioned_docs/version-1.2.0/quick_start/how_to_build.md
- Fixes #486
*(or)*
*(or)*
*(example:)* …
=> [INLONG-486][Doc] Update the download URLs in the guide

blog/2021-11-10-release-0.11.0.md, blog/2022-01-04-release-0.12.0.md, blog/2022-04-25-release-1.1.0.md, blog/2022-06-16-inlong-sort-etl.md, blog/2022-06-22-release-1.2.0.md, i18n/zh-CN/docusaurus-plugin-content-blog/2021-11-10-release-0.11.0.md, i18n/zh-CN/docusaurus-plugin-content-blog/2022-01-04-release-0.12.0.md, i18n/zh-CN/docusaurus-plugin-content-blog/2022-04-25-release-1.1.0.md, i18n/zh-CN/docusaurus-plugin-content-blog/2022-06-16-inlong-sort-etl.md, i18n/zh-CN/docusaurus-plugin-content-blog/2022-06-22-release-1.2.0.md, i18n/zh-CN/docusaurus-theme-classic/navbar.json
- Fixes https://github.com/apache/inlong-website/issues/483
=> [INLONG-483][Website] Chinese document display error

docs/design_and_concept/how_to_extend_data_node_for_manager.md, docs/design_and_concept/how_to_extend_data_node_for_sort.md, docs/design_and_concept/how_to_write_plugin_dashboard.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/how_to_extend_data_node_for_manager.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/how_to_extend_data_node_for_sort.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/how_to_write_plugin_dashboard.md
- Fixes #498
*(or)*
*(or)*
*(example:)* …
=> [INLONG-498][Doc] Unify the title for all plugin guide

docs/modules/dataproxy/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/quick_start.md
- Fixes https://github.com/apache/inlong-website/issues/505
=> [INLONG-505][Doc] Modify DataProxy configuration information

docs/modules/tubemq/configure_introduction.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/configure_introduction.md
- Fixes: https://github.com/apache/inlong/issues/5373
=> [INLONG-5373][TubeMQ] TubeMQ supports outputting traffic information through the audit SDK

docs/modules/agent/metrics.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/metrics.md
- Fixes #503 
Modify the indicator monitoring method of the agent module
=> [INLONG-503][Agent] The agent module specifies the indicator monitoring method

i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/configure_introduction.md
=> [INLONG-510][Improve] Adjust the format TubeMQ configuration document in the Chinese version

docs/modules/tubemq/configure_introduction.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/configure_introduction.md
- Fixes  https://github.com/apache/inlong/issues/5386
=> [INLONG-5386][TubeMQ] Supports reporting metrics data through Prometheus

docs/modules/tubemq/tubemq-manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/tubemq-manager/quick_start.md
- Fixes https://github.com/apache/inlong/issues/5282
=> [INLONG-5282][Doc] An error when deploying tubemq-manager according to the documentation on the official website

docs/modules/tubemq/tubemq-manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/tubemq-manager/quick_start.md
- Fixes https://github.com/apache/inlong-website/issues/514
=> [INLONG-514][Doc] Change the download link of the tube-manager deployment jar package

docs/user_guide/command_line_tools.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_guide/command_line_tools.md
Fixes [[Improve] Supplement command line tools information for inlong manager](https://github.com/apache/inlong-website/issues/520)
=> [INLONG-520][Manager] Supplement command line tools information for inlong manager

docs/deployment/bare_metal.md, docs/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/bare_metal.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/quick_start.md
- Fixes #524
*(or)*
*(or)*
*(example:)* …
=> [INLONG-524][Doc] Fix the invalid download URL

docs/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/quick_start.md
=> [INLONG-501][Doc] Add documentation for open api authentication

docs/deployment/docker.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/docker.md
- Fixes #526
*(or)*
*(or)*
*(example:)* …
=> [INLONG-526][Doc] Add flink cluster address configuration for docker-compose

docs/design_and_concept/how_to_extend_data_node_for_manager.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/how_to_extend_data_node_for_manager.md
=> [INLONG-516][DOC] Update Manager Plugin Design Doc

docs/modules/sort/quick_start.md, versioned_docs/version-1.2.0/modules/sort/quick_start.md
=> [INLONG-529][Doc] Optimize the quick start doc

config/team.json, src/pages/team/config.json
- Fixes #533
*(or)*
*(or)*
*(example:)* …
=> [INLONG-533][Doc] Add new committer for yunqing

docs/data_node/extract_node/kafka.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/kafka.md
- Fixes #541 
Modify doc for Importing all changelog mode data ingest into Kafka
docs/data_node/extract_node/kafka.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/kafka.md
=> [INLONG-541][Sort] Modify doc for importing all changelog data into Kafka

docs/data_node/extract_node/tube.md, docs/modules/agent/overview.md, docs/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/tube.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/quick_start.md
Add TubeMQ connector docs and update Agent docs.
- Fixes #537 
No message
No message
*(or)*
*(or)*
=> [INLONG-537][Sort][Agent] Add TubeMQ connector docs and update Agent docs

docs/data_node/load_node/elasticsearch.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/elasticsearch.md
- Fixes #539 
Modify doc for support routing field for Elasticsearch connector
docs/data_node/load_node/elasticsearch.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/elasticsearch.md
=> [INLONG-539][Sort] Modify doc for support routing field for Elasticsearch connector

docs/data_node/extract_node/pulsar.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/pulsar.md
[INLONG-546][Sort] Modify doc for pulsar support ingest data without admin url
*[INLONG-546][Sort] Modify doc for pulsar support ingest data without admin url*
- Fixes #546
=> [INLONG-546][Sort] Modify doc for Pulsar support ingests data without admin URL

docs/data_node/load_node/clickhouse.md, docs/data_node/load_node/greenplum.md, docs/data_node/load_node/oracle.md, docs/data_node/load_node/postgresql.md, docs/data_node/load_node/sqlserver.md, docs/data_node/load_node/tdsql-postgresql.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/clickhouse.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/greenplum.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/oracle.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/postgresql.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/sqlserver.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/tdsql-postgresql.md
*[INLONG-544][Sort] Modify doc for jdbc support ingest all changelog data*
- Fixes #544
=> [INLONG-544][Sort] Modify doc for JDBC support ingest all changelog data

blog/2022-09-05-release-1.3.0.md
- Fixes #549 
[INLONG-549][Bug] fix release doc bug on release-1.3.0
[INLONG-549][Bug] fix release doc bug on release-1.3.0
=> [INLONG-549][Bug] Fix release doc bug on release-1.3.0

docs/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.3.0/deployment/standalone.md, versioned_docs/version-1.3.0/deployment/standalone.md
- Fixes #553
*(or)*
*(or)*
*(example:)* …
=> [INLONG-553][Doc] Optimize the standalone deployment guide

docs/data_node/load_node/doris.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/doris.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.3.0/data_node/load_node/doris.md, versioned_docs/version-1.3.0/data_node/load_node/doris.md
- Fixes #555
*(or)*
*(or)*
*(example:)* …
=> [INLONG-555][Doc] Change the title for Doris

docusaurus.config.js
- Fixes https://github.com/apache/inlong-website/issues/557
=> [INLONG-557][Website] Optimize the navigation bar document column

docs/modules/sort-standalone/elasticsearch_example.md, docs/modules/sort-standalone/hive_example.md, docs/modules/sort-standalone/overview.md, docs/modules/sort-standalone/quick_start.md
- Fixes #560 
*(or)*
*(or)*
*(example:)* …
=> [INLONG-560][Doc] Update supported sinks and sources of sort-standalone

docs/introduction.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/basic_concept.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/introduction.md
- Fixes #566
*(or)*
*(or)*
*(example:)* …
=> [INLONG-566][Doc] Update the Introduction

docs/modules/manager/configure.md, docs/modules/manager/overview.md, docs/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/configure.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/quick_start.md
Create the configuration document for manager
- Fixes #568 
Create the configuration document for manager
Create the configuration document for manager
=> [INLONG-568][Doc] Create the configuration document for manager

docs/modules/agent/configure.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/configure.md
- Title Example: [INLONG-6196][Doc] Add Configuration doc for Agent
- Fixes #https://github.com/apache/inlong/issues/6196
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with large …
=> [INLONG-6196][Doc] Add configuration doc for Agent

docs/modules/audit/configure.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/configure.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/configuration.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/configure.md
- [INLONG-574][Audit]Update configuration item description
- Fixes #574
Update configuration item description
=> [INLONG-574][Audit] Update configuration item description

docs/user_guide/command_line_tools.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_guide/command_line_tools.md
- Fixes #572 
Update command tools document
=> [INLONG-572][Doc] Update command tools document

docs/data_node/extract_node/oracle-cdc.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/oracle-cdc.md
- Fixes #579
Add doc for oracle connector for all migrate
=> [INLONG-579][Doc] Add doc for oracle connector for all migrate

community/how-to-release.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-release.md
- Fixes #598
*(or)*
*(or)*
*(example:)* …
=> [INLONG-598][Doc] Update the how to release guide for Apache InLong

package.json
- Fixes #596
*(or)*
*(or)*
*(example:)* …
=> [INLONG-596] Bump docusaurus to 2.2.0

community/how-to-release.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-release.md
- Fixes #598
*(or)*
*(or)*
*(example:)* …
=> [INLONG-598][Doc] Update the how to release guide for Apache InLong(addendum)

docs/data_node/load_node/iceberg.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/iceberg.md
[INLONG-591][Doc] Add document for multiple sink of iceberg
- Add document for multiple sink of iceberg
- Fixes #591 
*Add document for multiple sink of iceberg.*
*Add document for multiple sink of iceberg.*
=> [INLONG-591][Doc] Add document for multiple sink of iceberg

docs/deployment/bare_metal.md, docs/deployment/docker.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/bare_metal.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/docker.md
- Fixes #606 
Add an entrance guide for Standard and Lightweight Architecture.
=> [INLONG-606][Doc] Add an entrance guide for Standard and Lightweight Architecture

docs/data_node/extract_node/overview.md, docs/data_node/load_node/overview.md, docs/deployment/bare_metal.md, docs/modules/sort/example.md, docs/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/bare_metal.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/example.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.4.0/data_node/extract_node/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.4.0/data_node/load_node/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.4.0/deployment/bare_metal.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.4.0/modules/sort/example.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.4.0/modules/sort/quick_start.md, versioned_docs/version-1.4.0/data_node/extract_node/overview.md, versioned_docs/version-1.4.0/data_node/load_node/overview.md, versioned_docs/version-1.4.0/deployment/bare_metal.md, versioned_docs/version-1.4.0/modules/sort/example.md, versioned_docs/version-1.4.0/modules/sort/quick_start.md
- Fixes #609
*(or)*
*(or)*
*(example:)* …
=> [INLONG-609][Doc] Connect all Sort-related document guides

blog/2021-11-10-release-0.11.0.md, blog/2022-01-04-release-0.12.0.md, blog/2022-04-25-release-1.1.0.md, blog/2022-06-22-release-1.2.0.md, blog/2022-09-05-release-1.3.0.md, blog/2022-11-16-release-1.4.0.md, i18n/zh-CN/docusaurus-plugin-content-blog/2022-11-16-release-1.4.0.md
- Fixes #590
*(or)*
*(or)*
*(example:)* …
=> [INLONG-590][Release] Add blog for the 1.4.0 release

src/pages/downloads/download.module.less, src/pages/downloads/index.js
- Fixes https://github.com/apache/inlong-website/issues/617
=> [INLONG-617] Download page font night mode display problem

community/how-to-commit.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-commit.md
- Fixes #621
*(or)*
*(or)*
*(example:)* …
=> [INLONG-621][Doc] Update the how-to-commit guide

community/how-to-release.md, community/how-to-verify.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-verify.md
- Fixes #628 
Update the How to verify release candidate guide
=> [INLONG-628][Doc] Update the How to verify release candidate guide

docs/introduction.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/introduction.md
- Fixes https://github.com/apache/inlong-website/issues/630
=> [INLONG-630][Doc] Update the supported Extract Node table

docs/sdk/dataproxy-sdk/cpp.md
https://github.com/apache/inlong-website/issues/625
- Fixes #625
Translate C++ SDK report guide
=> INLONG-625][Doc] Translate C++ SDK report guide

docs/sdk/dataproxy-sdk/http.md
[[INLONG-627] [Doc] Translate http report guide]
Fixes #627
translate http report guide
=> [INLONG-627] [Doc] Translate http report guide (#627)

docs/data_node/load_node/elasticsearch.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/elasticsearch.md
- Fixes #638
*(or)*
*(or)*
*(example:)* …
=> [INLONG-638][sort] Add support for elasticsearch-5

docs/modules/tubemq/client_rpc.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/client_rpc.md
- Fixes #642 
Current docs for tubemq  RPC are not formatted, this PR tries to fix this problem
format docs for tubemq rpc, replace screenshot with code snippet
=> [INLONG-642][Doc] Reformat docs for tubemq rpc

docs/sdk/dataproxy-sdk/java.md
- Title: [INLONG-626][Doc] Translate Java SDK report guide
- Fixes #626 
Translate Java SDK report guide.
Translate.
=> [INLONG-626][Doc] Translate Java SDK report guide

docs/data_node/load_node/starrocks.md, docs/introduction.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/starrocks.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/introduction.md
- Fixes #645
*(or)*
*(or)*
*(example:)* …
=> [INLONG-645][Doc] Starrocks load node documents

docs/data_node/extract_node/postgresql-cdc.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/postgresql-cdc.md
- Fixes #636
*(or)*
*(or)*
*(example:)* …
=> [INLONG-636][Doc] Postgresql cdc suggest setting replica identity to FULL

docs/contact.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/contact.md
- Fixes #653
*(or)*
*(or)*
*(example:)* …
=> [INLONG-653][Doc] Update the Contact Us guide

community/how-to-vote-a-committer-pmc.md, docs/contact.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/contact.md
- Fixes #655
*(or)*
*(or)*
*(example:)* …
=> [INLONG-655][Doc] Fix some show problems

docs/sdk/tubemq-sdk/_category_.json, docs/sdk/tubemq-sdk/cpp.md, docs/sdk/tubemq-sdk/python.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/tubemq-sdk/cpp.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/tubemq-sdk/python.md
This PR for #659, add documents for c++/python sdk in en/zh-cn two languages.
=> [INLONG-659][Doc] Add docs for c++/python sdk.

docusaurus.config.js, i18n/zh-CN/docusaurus-theme-classic/footer.json
- Fixes https://github.com/apache/inlong/issues/7188
=> [INLONG-7188][Doc] Change the project Copyright to 2019-2023

docs/data_node/load_node/clickhouse.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.4.0/data_node/load_node/clickhouse.md
- [INLONG-665][Sort] Update clickhouse about usage
- Fixes #665 
*  Update clickhouse about usage
* update clickhosue date node
=> [INLONG-665][Sort] Update clickhouse usage page

src/pages/downloads/download.module.less, src/pages/downloads/index.js
- Fixes https://github.com/apache/inlong-website/issues/673
=> [INLONG-673] Download page style optimization

blog/2023-01-13-release-1.5.0.md, community/how-to-release.md, community/how-to-vote-a-committer-pmc.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-release.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-vote-a-committer-pmc.md
- Fixes #680
*(or)*
*(or)*
*(example:)* …
=> [INLONG-680][Doc] Update how-to-release and how-to-vote-a-committer-pmc

docs/deployment/docker.md, docs/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/docker.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/standalone.md
- Fixes #687
*Explain here the context, and why you're making that change. What is the problem you're trying to solve?*
This change is a trivial rework/code cleanup without any test coverage.
*(or)*
*(or)*
*(example:)*
- *Extended integration test …
=> [INLONG-687][Doc] Optimize the standalone deployment guide

docs/data_node/extract_node/oracle-cdc.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/oracle-cdc.md
Add incremental snapshot doc for oracle cdc
- Fixes #689 
Add incremental snapshot doc for oracle cdc.
Add some options description. These options are as follows:
```xml
enableParallelRead
splitSize
splitMetaGroupSize
fetchSize
connectTimeout
connectMaxRetries
connectionPoolSize
distributionFactorUpper
distributionFactorLower
chunkKeyColumn
```
=> [INLONG-689][Doc] Add incremental snapshot doc for oracle cdc

docs/deployment/k8s.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/k8s.md
- Fixes #695
Update the address
=> [INLONG-695][Doc] Update the guide for deploying by k8s

docs/deployment/k8s.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/k8s.md
- Fixes #7447
Make the Pulsar the default MQ option to lower the complexity
=> [INLONG-7447][Docker] Make the Pulsar the default MQ option to lower the complexity

docs/modules/dataproxy/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dataproxy/quick_start.md
- Fixes #698
Update the DataProxy deployment guide, and correct some description errors
=> [INLONG-698][Doc] Update the DataProxy deployment guide, and correct some description errors

package.json
- Fixes #700
Bump the docusaurus to 2.3.1 to fix the build error.
=> [INLONG-700][Build] Bump docusaurus to 2.3.1

docs/modules/audit/configure.md, docs/modules/audit/overview.md, docs/modules/audit/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/configure.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/quick_start.md
- Fixes #704 
Add documentation for using Kafka.
Add documentation for using Kafka.
=> [INLONG-704][Doc] Add Kafka document for Audit

docs/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/standalone.md
- Fixes https://github.com/apache/inlong/issues/7528
Add the Kafka support for audit standalone deployment
=> [INLONG-7528][Doc] Add the Kafka support for audit standalone deployment

docs/data_node/extract_node/oracle-cdc.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/oracle-cdc.md
[INLONG-708][Doc] Describe Oracle CDC using Markdown
- Fixes #708 
Describe Oracle CDC using Markdown
=> [INLONG-708][Doc] Describe Oracle CDC using Markdown

docs/data_node/extract_node/mongodb-cdc.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/mongodb-cdc.md
- Title Example: [INLONG-707][Doc] Add parameter description for enabling incremental snapshot for MongoDB CDC
- Fixes #707 
Add parameter description for enabling incremental snapshot for MongoDB CDC
1. Add description.
2. pls see the pr https://github.com/apache/inlong/pull/7588 .
=> [INLONG-707][Doc] Add parameter description for enabling incremental snapshot for MongoDB CDC

docs/modules/dashboard/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/dashboard/overview.md
- Fixes https://github.com/apache/inlong-website/issues/715
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with …
=> [INLONG-715][Doc] Optimize Dashboard overview document

config/team.json
- Fixes https://github.com/apache/inlong-website/issues/738
=> [INLONG-738] Update the PMC and committer of the Team page

docs/user_guide/command_line_tools.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_guide/command_line_tools.md
- Fixes #740 
Update `suspend` and `restart` docs
Add `suspend` and `restart` docs
=> [INLONG-740][Doc] Add suspend and restart command docs

docs/user_guide/command_line_tools.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_guide/command_line_tools.md
- Fixes #742 
Add create group command docs
Add create group command docs
=> [INLONG-742][Doc] Add create group command docs

docs/version.js, i18n/zh-CN/docusaurus-plugin-content-docs/current/version.js, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.3.0/version.js, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.4.0/version.js, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.5.0/version.js, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.6.0.json, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.6.0/version.js, versioned_docs/version-1.3.0/version.js, versioned_docs/version-1.4.0/version.js, versioned_docs/version-1.5.0/version.js, versioned_docs/version-1.6.0/version.js
- Fixes https://github.com/apache/inlong-website/issues/744
=> [INLONG-744][Doc] The version number does not match

src/pages/team/index.js
=> [INLONG-756] Attach avatars of Contributors

README.md
- Fixes #758 
I ran into some problems when I first ran the project against README.md, and I hope to refine them and make it less difficult for others to use.
Modify only the README.md file
=> [INLONG-758][Doc] Change the README.md file

docs/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2.0/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.3.0/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.4.0/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.5.0/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.6.0/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.7.0/modules/manager/quick_start.md, versioned_docs/version-1.2.0/modules/manager/quick_start.md, versioned_docs/version-1.3.0/modules/manager/quick_start.md, versioned_docs/version-1.4.0/modules/manager/quick_start.md, versioned_docs/version-1.5.0/modules/manager/quick_start.md, versioned_docs/version-1.6.0/modules/manager/quick_start.md, versioned_docs/version-1.7.0/modules/manager/quick_start.md
- Fixes #762 
Hopefully it will jump to the correct address
Change https://inlong.apache.org/download/main to https://inlong.apache.org/download
=> [INLONG-762][Doc] Connector Binary file link address error

docs/design_and_concept/how_to_extend_data_node_for_manager.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/how_to_extend_data_node_for_manager.md
[INLONG-770][Doc]Update design and concept extending data node for manager
- Fixes #770
Update design and concept extending data node for manager by https://github.com/apache/inlong/pull/8181
=> [INLONG-770][Doc] Update design and concept extending data node for manager

docs/sdk/dataproxy-sdk/http.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/dataproxy-sdk/http.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.5.0/sdk/dataproxy-sdk/http.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.6.0/sdk/dataproxy-sdk/http.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.7.0/sdk/dataproxy-sdk/http.md, versioned_docs/version-1.5.0/sdk/dataproxy-sdk/http.md, versioned_docs/version-1.6.0/sdk/dataproxy-sdk/http.md, versioned_docs/version-1.7.0/sdk/dataproxy-sdk/http.md
=> [INLONG-777][SDK] Fix error in determining the return code of the HTTP SDK sending interface for DataProxy

community/how-to-release.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-release.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/user_guide/dashboard_usage.md
- Fixes #779
Update the how-to-release guide for multi-version connectors
=> [INLONG-779][Doc] Update the how-to-release guide for multi-version connectors

docs/data_node/load_node/hive.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/hive.md
- Fixes #784, #776 
*(or)*
*(or)*
*(example:)*
- *Extended …
=> [INLONG-784][Doc][Hive] Describe tables using MarkDown

docs/data_node/load_node/elasticsearch.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/elasticsearch.md
[INLONG-782][Doc][Elasticsearch] Describe tables using MarkDown
- Fixes #782
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / …
=> [INLONG-782][Doc][Elasticsearch] Describe tables using MarkDown

docs/sdk/tubemq-sdk/go.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/tubemq-sdk/go.md
This PR for #793, add documents for tubemq go sdk in en/zh-cn two languages.
=> [INLONG-793][Doc] Add docs for tubemq go sdk.

community/how-to-vote-a-committer-pmc.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-vote-a-committer-pmc.md
- Fixes #797 
Improve the email template for hot-to-vote-committer-pmc
remove duplicated indefinite article
- Does this pull request introduce a new feature? ( no)
=> [INLONG-797][Doc] Improve the email template for hot-to-vote-committer-pmc

docs/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/quick_start.md
- Fixes #803 
Update manager multi-flink version document
Add flink version option
=> [INLONG-803][Doc] Update manager multi-flink version document

docs/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/quick_start.md
- Fixes #812 
Update sort document for multi-flink version
Add notes when changing the Flink version
=> [INLONG-812][Doc] Update sort document for multi-flink version

src/pages/downloads/download.module.less, src/pages/downloads/index.js
- Fixes https://github.com/apache/inlong-website/issues/806
=> [INLONG-806] Download page optimization download button

src/pages/downloads/download.module.less, src/pages/downloads/index.js
- Fixes https://github.com/apache/inlong-website/issues/816
=> [INLONG-816] Download page binary download option optimization

i18n/zh-CN/docusaurus-plugin-content-blog/2023-07-24-release-1.8.0.md
- Fixes https://github.com/apache/inlong-website/issues/818
=> [INLONG-818] Blog display optimization

docs/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/standalone.md
- Fixes #820 
*(or)*
*(or)*
*(example:)* …
=> [INLONG-820][Doc] Add deployment os require

docs/deployment/standalone.md, docs/modules/agent/quick_start.md, docs/modules/audit/quick_start.md, docs/modules/manager/quick_start.md, docs/modules/tubemq/tubemq-manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/tubemq-manager/quick_start.md
- Fixes #824 
Update Mysql-connector version information.
Update Mysql-connector version information.
*(or)*
*(or)*
*(example:)*
- Does this pull …
=> [INLONG-824][Doc] Update Mysql-connector version information

docs/data_node/extract_node/oracle-cdc.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/oracle-cdc.md
[INLONG-835][Doc] Fix Oracle document errors
- Fixes #835 
Fix Oracle document errors.
=> [INLONG-835][Doc] Fix Oracle document errors

docs/modules/tubemq/commandline_tools.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/tubemq/commandline_tools.md
- Fixes #845
*Upload documents, chinese and english.*
*Upload documents, chinese and english.*
=> [INLONG-845][Doc] Add Command Line tools guide for TubeMQ

src/pages/downloads/download.module.less, src/pages/downloads/index.js
- Fixes https://github.com/apache/inlong-website/issues/841
1920*1080
=> [INLONG-841] Download page display error on a small screen

docs/sdk/dataproxy-sdk/cpp.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/dataproxy-sdk/cpp.md
- Fixes #852 
*Update dataproxy cpp sdk usage documentation.*
*Update dataproxy cpp sdk usage documentation.*
=> [INLONG-852][SDK] Update dataproxy cpp sdk usage documentation

docs/data_node/load_node/sqlserver.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/sqlserver.md
- Fixes #868 
*(or)*
*(or)*
*(example:)* …
=> [INLONG-868][Sort] Fix typo in sqlserver part

i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/starrocks.md
Fix the document for the starrocks load node
- Fixes #870 
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with …
=> [INLONG-870][Sort] Update starrocks.md

docs/data_node/load_node/redis.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/redis.md
- Fixes #864 
*(or)*
*(or)*
*(example:)* …
=> [INLONG-864][Sort] Add redis information

docs/data_node/extract_node/mysql-cdc.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/mysql-cdc.md
- Fixes #880 
When using MySQL with version above 8.0, there is a easily caused problem. And flink error may be hard to find, some I think we can add in the attention part.  
Add attention description.  
*(or)*
*(or)*
*(example:)*
- If a …
=> [INLONG-880][Sort] Add some attention in Mysql cdc

docs/sdk/dataproxy-sdk/go.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/dataproxy-sdk/go.md
- Fixes #886
Update the default values of the config options.
Update the default values of the config options.
*(or)*
*(or)*
*(example:)*
- If a feature is not documented …
=> [INLONG-886][Doc] Update DataProxy Golang SDK docs

docs/sdk/dataproxy-sdk/java.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/dataproxy-sdk/java.md
- Fixes #888 
Update DataProxy JAVA SDK docs
The details can be found at [#8281 ](https://github.com/apache/inlong/issues/888).
=> [INLONG-888][Doc] Update DataProxy JAVA SDK docs

community/how-to-release.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-release.md
- Fixes #900 
Due to https://github.com/apache/inlong/pull/9451 having deployed all connectors to the maven repo, we don't need to publish the connectors when releasing.
=> [INLONG-900][Doc] Remove connectors copy in how-to-release doc

docs/quick_start/data_sync/mysql_clickhouse_example.md, docs/quick_start/data_sync/mysql_iceberg_example.md, docs/quick_start/data_sync/mysql_starrocks_example.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/data_sync/mysql_clickhouse_example.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/data_sync/mysql_iceberg_example.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/data_sync/mysql_starrocks_example.md
- Fixes #916 
Optimize document description
Optimize document description
=> [INLONG-916][Doc] Optimize document description

docs/deployment/bare_metal.md, docs/deployment/k8s.md, docs/deployment/standalone.md, docs/modules/sort/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/bare_metal.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/k8s.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/standalone.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/sort/quick_start.md
- Fixes #924
Update the deployment guide for support Flink 1.15
Update the deployment guide for support Flink 1.15
=> [INLONG-924][Doc] Update the deployment guide for support Flink 1.15

docusaurus.config.js, i18n/zh-CN/docusaurus-theme-classic/footer.json
- Fixes #934 
update copyright date to 2024
=> [Improve-934][doc] update copyright date to 2024

docs/modules/audit/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/quick_start.md
Fixes https://github.com/apache/inlong/issues/10122
due to https://github.com/apache/inlong/pull/10090 has change apache_inlong_audit.sql to apache_inlong_audit_mysql.sql, but there are some places missed.
due to https://github.com/apache/inlong/pull/10090 has change apache_inlong_audit.sql to apache_inlong_audit_mysql.sql, but there are some places missed.
=> [INLONG-10122][Audit] Update the apache_inlong_audit.sql to apache_inlong_audit_mysql.sql

docs/deployment/bare_metal.md, docs/modules/agent/configure.md, docs/modules/agent/overview.md, docs/modules/agent/quick_start.md, docs/modules/audit/quick_start.md, docs/modules/manager/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/deployment/bare_metal.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/configure.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/agent/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/quick_start.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/manager/quick_start.md
Fixes #954
Update the deployment and configuration guides for the latest version
Update the deployment and configuration guides for the latest version
=> [INLONG-954][Doc] Update the deployment and configuration guides for the latest version

docs/design_and_concept/how_to_write_plugin_agent.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/design_and_concept/how_to_write_plugin_agent.md
Fixes #957 
Supplement Agent plugin documentation
Supplement Agent plugin documentation
Chinese：
English：
=> [INLONG-957][Doc] Supplement Agent plugin documentation

docusaurus.config.js
Fixes #966
Remove old version doc.
Remove old version doc.
=> [INLONG-966][Doc] Remove old version doc

docs/quick_start/data_sync/mysql_starrocks_example.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/data_sync/mysql_starrocks_example.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.10.0/quick_start/data_sync/mysql_starrocks_example.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.11.0/quick_start/data_sync/mysql_starrocks_example.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.12.0/quick_start/data_sync/mysql_starrocks_example.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-1.13.0/quick_start/data_sync/mysql_starrocks_example.md, versioned_docs/version-1.10.0/quick_start/data_sync/mysql_starrocks_example.md, versioned_docs/version-1.11.0/quick_start/data_sync/mysql_starrocks_example.md, versioned_docs/version-1.12.0/quick_start/data_sync/mysql_starrocks_example.md, versioned_docs/version-1.13.0/quick_start/data_sync/mysql_starrocks_example.md
Fixes #970 
current `Apache starrocks` to `Starrocks`
- Does this pull request introduce a new feature? ( no)
=> [INLONG-970][Doc] fix the wrong referring to StarRocks

docs/sdk/dataproxy-sdk/python.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/dataproxy-sdk/python.md
=> [INLONG-982][Doc] Add DataProxy SDK document of Python

docs/data_node/extract_node/doris.md, docs/data_node/extract_node/iceberg.md, docs/data_node/extract_node/overview.md, docs/data_node/load_node/doris.md, docs/data_node/load_node/iceberg.md, docs/data_node/load_node/overview.md, docs/data_node/load_node/starrocks.md
=> [INLONG-1000][Doc] Update Extract and Load Node version

docs/quick_start/transform/_category_.json, docs/quick_start/transform/sdk_example.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/quick_start/transform/sdk_example.md
=> [INLONG-1017][Doc] Add quick-start document of Transform.

docs/introduction.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/introduction.md
Fixes #1025 
Update data nodes in introduction
Update data nodes in introduction
- Does this pull request introduce a new feature? (yes )
=> [INLONG-1025][Doc] Update data nodes in introduction

docs/modules/audit/overview.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/modules/audit/overview.md
- Fixes #1041
Update audit documentation instructions
Introduction to new audit data storage
=> [INLONG-1041][Audit] Update audit documentation instructions

docs/data_node/extract_node/kafka.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/extract_node/kafka.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/data_node/load_node/elasticsearch.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0.0/data_node/load_node/elasticsearch.md, i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0.0/data_node/load_node/kafka.md, versioned_docs/version-2.0.0/data_node/extract_node/kafka.md
Fixes #1083
The text description is inconsistent with the Flink SQL below.
Correct the description of connector name for sort-connector kafka
=> [INLONG-1083][Doc] Correct description of connector name for sort-connector Kafka and ElasticSearch

community/how-to-vote-a-committer-pmc.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-vote-a-committer-pmc.md
=> [INLONG-1100][Doc] Fix the contribution link of How to Vote a Committer or PMC Member

community/how-to-vote-a-committer-pmc.md, i18n/zh-CN/docusaurus-plugin-content-docs-community/current/how-to-vote-a-committer-pmc.md
=> [INLONG-1112][Doc] Update the PMC & Committer voting document

docs/sdk/dataproxy-sdk/java.md, i18n/zh-CN/docusaurus-plugin-content-docs/current/sdk/dataproxy-sdk/java.md
Fixes #1114
Update the corresponding documentation according to the latest DataProxy Java SDK implementation
=> [INLONG-1114][Doc] Update the DataProxy Java SDK documentation

.asf.yaml
=> [INLONG-1122][Workflow] Require at least two reviewers approve before merging
